name: ccst
channels:
  - defaults
dependencies:
  - numpy=1.19.2
  - pandas=1.2.3
  - scikit-learn=0.24.1
  - matplotlib=3.3.4
  - scipy=1.7.0
  - pytorch=1.7.1
  - torchvision
  - torchaudio
  - cpuonly
  - seaborn=0.11.1
  - scanorama=1.7.1
  - openpyxl=3.0.7
  - umap-learn=0.5.1
  - stlearn=0.3.2
  - pip:
    - torch-geometric==1.6.3
    - torch-sparse==0.6.8
    - torch-scatter==2.0.5
